export const enum SubscriptionStatus {
  PREACTIVE = 'PREACTIVE',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
  DEACTIVATED = 'DEACTIVATED',
  SUBSPENDED = 'SUBSPENDED'
}
